name: aut_all_research
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_min_gpl: 6.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  image: ^4.2.0
  video_player: ^2.9.1
  opencv_dart: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
