name: aut_all_research
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_min_gpl: 6.0.3
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  image: ^4.2.0
  video_player: ^2.9.1
  delaunay: ^2.0.0
  dio: ^5.6.0
  depth_map_reader:
    path: ../depth_map_reader
  flutter_zxing: ^1.7.0
  injectable: ^2.4.4
  flutter_local_notifications: ^17.2.2
  get_it: ^7.7.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  timezone: ^0.9.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner:
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/offsets/
